# Generated by Django 5.1.2 on 2024-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('numero_paginas', models.PositiveIntegerField(verbose_name='Número de Páginas')),
            ],
        ),
    ]
